service: hello

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  
functions:
  hello:
    handler: src/handlers/index.handler
    events:
      - http:
          method: GET
          path: /hello

custom:
  bundle:
  linting: false
